# file      : tests/basic/buildfile
# copyright : Copyright (c) 2009-2017 Code Synthesis Tools CC
# license   : GPLv2 with FOSS License Exception; see accompanying COPYING file

import libs = libmysqlclient%lib{mysqlclient}

exe{driver}: {h c}{*} $libs test{testscript}
