# file      : tests/basic/buildfile
# copyright : Copyright (c) 2009-2019 Code Synthesis Tools CC
# license   : GPLv2 with Universal FOSS Exception; see accompanying LICENSE file

import libs = libmysqlclient%lib{mysqlclient}

exe{driver}: {h c}{*} $libs testscript
